"""add images to news

Revision ID: 5b925916f733
Revises: 8b65a5af682d
Create Date: 2023-12-06 00:38:28.478948

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b925916f733'
down_revision = '8b65a5af682d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('address_uz', sa.String(length=255), nullable=True))
    op.add_column('events', sa.Column('address_en', sa.String(length=255), nullable=True))
    op.add_column('events', sa.Column('address_ru', sa.String(length=255), nullable=True))
    op.drop_column('events', 'address')
    op.add_column('news', sa.Column('images', sa.String(), nullable=True, comment='Array of image urls'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('news', 'images')
    op.add_column('events', sa.Column('address', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('events', 'address_ru')
    op.drop_column('events', 'address_en')
    op.drop_column('events', 'address_uz')
    # ### end Alembic commands ###
