"""add new field to event

Revision ID: 97b6c2980ec2
Revises: 0e9ade249bce
Create Date: 2023-12-21 11:55:53.599659

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97b6c2980ec2'
down_revision = '0e9ade249bce'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('phone', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'phone')
    # ### end Alembic commands ###
