"""add date to grands

Revision ID: be256889ccc7
Revises: 5b925916f733
Create Date: 2023-12-06 12:34:54.156498

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be256889ccc7'
down_revision = '5b925916f733'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('grands', sa.Column('from_date', sa.Date(), nullable=True, comment='grant application deadline'))
    op.add_column('grands', sa.Column('to_date', sa.Date(), nullable=True, comment='grant application deadline'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('grands', 'to_date')
    op.drop_column('grands', 'from_date')
    # ### end Alembic commands ###
