"""remove unieq from orderes

Revision ID: 5ec961865673
Revises: f8a070b9404c
Create Date: 2024-09-06 15:44:01.616286

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ec961865673'
down_revision = 'f8a070b9404c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_user_product', 'orders', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('unique_user_product', 'orders', ['user_id', 'product_id'])
    # ### end Alembic commands ###
