"""update fields as opstional

Revision ID: e106b4f0f031
Revises: 97b6c2980ec2
Create Date: 2024-01-20 10:23:14.000488

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e106b4f0f031'
down_revision = '97b6c2980ec2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('categories', 'name_en',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('categories', 'name_uz',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('cities', 'name_uz',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('cities', 'name_en',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('events', 'name_uz',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('events', 'name_en',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('faqs', 'name_uz',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('faqs', 'name_en',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('grands', 'name_en',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('grands', 'name_uz',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('news', 'name_uz',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('news', 'name_en',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('products', 'name_en',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('products', 'name_uz',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'name_uz',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('products', 'name_en',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('news', 'name_en',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('news', 'name_uz',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('grands', 'name_uz',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('grands', 'name_en',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('faqs', 'name_en',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('faqs', 'name_uz',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('events', 'name_en',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('events', 'name_uz',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('cities', 'name_en',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('cities', 'name_uz',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('categories', 'name_uz',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('categories', 'name_en',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###
