"""orders changed add status

Revision ID: f8a070b9404c
Revises: 2fbde4a8e695
Create Date: 2024-09-06 13:20:54.056024

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8a070b9404c'
down_revision = '2fbde4a8e695'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('order_status', sa.Enum('new', 'in_progress', 'completed', 'canceled', 'ready', name='order_status'), nullable=True))
    op.add_column('orders', sa.Column('count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'count')
    op.drop_column('orders', 'order_status')
    # ### end Alembic commands ###
