"""new field event

Revision ID: 80afd1527ebf
Revises: d7431433537a
Create Date: 2024-03-12 00:32:48.933012

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80afd1527ebf'
down_revision = 'd7431433537a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('is_exist_free_places', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'is_exist_free_places')
    # ### end Alembic commands ###
