"""add device token

Revision ID: 172013117e71
Revises: e106b4f0f031
Create Date: 2024-01-24 15:22:00.634098

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '172013117e71'
down_revision = 'e106b4f0f031'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('device_token', sa.String(length=255), nullable=True, comment='Device token for push notifications used by firebase'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'device_token')
    # ### end Alembic commands ###
